### ISSUE TITLE
Ressource not found message

### ISSUE THREAD

**Issue by Or1j1n** [darvid/stashvision#1]
Hey,

I'm pretty sure everything is set up correctly but i'm getting a ressource not found message

time="2020-01-07T12:17:32+01:00" level=debug msg="opening index" indexName=stash_tabs.bleve
time="2020-01-07T12:17:32+01:00" level=info msg="getting stash items" accountName=_XXXX_ league=blight tabIndex=1 tabs=0
time="2020-01-07T12:17:32+01:00" level=info msg="request started" path=/character-window/get-stash-items
time="2020-01-07T12:17:33+01:00" level=info msg="request complete" cost=0s length=51 path=/character-window/get-stash-items
time="2020-01-07T12:17:33+01:00" level=error msg="got error response from API" accountName=_XXXX_  errorCode=1 errorMessage="Resource not found" 

Any chance you might point me in the right direction to solve this ?

**Comment by darvid** [comment]
I think it's from `blight` being hardcoded as the league in `stashvision.go` -- updating that to `metamorph` and recompiling `stashvision.exe` with Go should work. I might have time tonight to add it as a configuration value as it should be, and cut a new release soon.

**Comment by Or1j1n** [comment]
Thanks for the quick reply and the upcoming update.

**Comment by darvid** [comment]
Sorry for the delay, just released [0.1.1](https://github.com/darvid/stashvision/releases/tag/v0.1.1) which should resolve this and a couple other bugs as well.
