### ISSUE TITLE
Overlay misaligned 

### ISSUE THREAD

**Issue by Turinqui** [darvid/stashvision#2]
As per attached screenshot, the overlay created appears to be slightly too large, causing misalignment. My desktop and in game resolution are both 1920x1080
![PathOfExile_x64_2020-01-12_01-48-12](https://user-images.githubusercontent.com/40512934/72210887-1a004780-3516-11ea-9f51-b8e33b3d94fb.png)

**Comment by darvid** [comment]
hmm, are you using windowed full screen, bordered, or full screen?

**Comment by darvid** [comment]
also, can you verify that `DumpTabQuad` is set to true in your config file?

**Comment by Turinqui** [comment]
In game settings: Windowed Fullscreen
stashvision.ini: DumpTabQuad = true

**Comment by darvid** [comment]
thanks! I'm working on a fix that will work across window sizes and resolutions, until then as a workaround you can update the `stashvision.ahk` file and play around with some of the values for the sizing of the highlight rectangle and the positions.

the size is this block on line 167:

```
    if isQuadTab {
        rectWidth := 35
        rectHeight := 35
    } else {
        rectWidth := 70
        rectHeight := 70
    }
```

(that's the width and height of one single square in a stash tab)

and the function at line 118 influences the starting X and Y position for the top left corner of the stash:

```
GetStashPosition(ByRef stashX, ByRef stashY, ByRef stashWidth, ByRef stashHeight) {
    WinGetPos, poeX, poeY, poeWidth, poeHeight, Path of Exile
    stashX := 23
    stashY := Round(poeHeight * 0.15)
    stashWidth := Round(poeWidth * 0.33)
    stashHeight := poeHeight - stashY - 380
}
```

from your screenshot, it looks like the Y position is fine, but the X is off a bit. you should be able to fix that by changing `stashX`.

I will try to get a fix for this pushed soon, but hopefully that's enough information if you're inclined to get it quickly working yourself.

**Comment by Turinqui** [comment]
Perfect, 

I did dig through the code a little and had a look at another addon that utilises a stash highlight overlay - [(POE-Trades-Companion)](https://github.com/lemasato/POE-Trades-Companion), I'll have a play and report back!

**Comment by Turinqui** [comment]
Got it pretty close:
https://i.imgur.com/1tsiyQj.jpg - https://i.imgur.com/FlAKZpn.jpg
I ended up changing the numbers around and testing - in case it helps here's what I ended up with:
```Autohotkey

GetStashPosition(ByRef stashX, ByRef stashY, ByRef stashWidth, ByRef stashHeight) {
    WinGetPos, poeX, poeY, poeWidth, poeHeight, Path of Exile
    stashX := 16
    stashY := Round(poeHeight * 0.15) ;=162
    stashWidth := Round(poeWidth * 0.33) ;1920*0.33 = 633
    stashHeight := poeHeight - stashY - 126 ;1080-162-126 = 792
}

```

```Autohotkey

    if isQuadTab {
        rectWidth := 26
        rectHeight := 26
    } else {
        rectWidth := 52
        rectHeight := 52
    }

```

**Comment by darvid** [comment]
oh cool, I had heard of trade companion but wasn't aware it highlighted items too - very interesting, and looks like the code for figuring out coordinates for highlighting across different resolutions is 
[very well documented](https://github.com/lemasato/POE-Trades-Companion/blob/master/lib/Class_GUI_ItemGrid.ahk). 

glad you got it to be usable, and thanks for the snippet!

huh...also looking at your screenshots, it seems like the chaos recipe is buggy too, it's highlighting identified items. I'll try to fix that as well in an upcoming update
