### ISSUE TITLE
league parameter isn't taken in account 

### ISSUE THREAD

**Issue by Scaaaar** [darvid/stashvision#6]
In my configuration.ini : "League = Standard" 

When trying to highlight : 
I have an error in the log file : "time="2020-06-19T01:02:00+02:00" level=error msg="got error response from API" accountName=XXXX errorCode=2 errorMessage="Invalid query" league=harvest tabIndex=0 tabs=0"

Using last version

**Comment by darvid** [comment]
doh - try **LeagueName** instead. I goofed the example ini

**Comment by Scaaaar** [comment]
No more errors ! 

If I don't see any highlight, it means I don't have enough items for a full set the stash right ?

**Comment by darvid** [comment]
yep, no highlight means not enough items for the recipe
